# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               PIMS Workshop
tagline:             'Discovery of Mathematical Sciences'
description:         'A web space supporting collaboration and chronicling activities for a workshop supported by PIMS.'
url:                 http://pims.math.ca
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Conference Organizer
  url:               https://twitter.com/pimsmath
  email:             info@pims.math.ca

# Custom vars
version:             1.0.0
