# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Setup
title:               PIMS Workshop
tagline:             'Mathematical Sciences Discovery'
description:         'A web space supporting collaboration and chronicling activities for a workshop supported by PIMS.'
url:                 http://pims.math.ca
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Conference Organizer
  url:               https://twitter.com/pimsmath
  email:             info@pims.math.ca

# Custom vars
version:             1.0.0

gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll/scholar

# Jekyll Scholar Configuration for handling Bibtex

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"